CREATE TABLE POLLUSER(
EMAILID VARCHAR(50),
PASSWORD VARCHAR(50),
USERID VARCHAR(20),
PRIMARY KEY (USERID), UNIQUE KEY (EMAILID)
);


CREATE TABLE POLL(
POLLID INTEGER AUTO_INCREMENT,
QUESTION VARCHAR(200),
OWNERID VARCHAR(50),
CREATED DATE,
STARTDATE DATE,
ENDDATE DATE,
TEXTMSG VARCHAR(50),
URL VARCHAR(50),
STATUS VARCHAR(20),
PRIMARY KEY (POLLID,TEXTMSG),
UNIQUE KEY (URL),
FOREIGN KEY (OWNERID) REFERENCES POLLUSER(USERID) ON DELETE CASCADE
);


CREATE TABLE CHOICE(
TEXT VARCHAR(50),
POLLID INTEGER,
CHOICEID INTEGER AUTO_INCREMENT,
PRIMARY KEY (POLLID,CHOICEID),
FOREIGN KEY (POLLID) REFERENCES POLL(POLLID) ON DELETE CASCADE
);


CREATE TABLE VOTE(
POLLID INTEGER,
CHOICEID INTEGER,
TIME TIMESTAMP DEFAULT NOW(),
PHONE INTEGER(20),
SESSIONID INTEGER(20),
COUNT INTEGER(10),
FOREIGN KEY (POLLID) REFERENCES POLL(POLLID) ON DELETE CASCADE,
FOREIGN KEY (CHOICEID) REFERENCES CHOICE(CHOICEID) ON DELETE CASCADE
);