
CREATE TABLE POLL(
POLLID INTEGER AUTO_INCREMENT,
QUESTION VARCHAR(200),
OWNERID integer,
CREATED DATE,
STARTDATE DATE,
ENDDATE DATE,
TEXTMSG VARCHAR(50),
URL VARCHAR(50),
STATUS VARCHAR(20),
PRIMARY KEY (POLLID,TEXTMSG),
UNIQUE KEY (URL),
FOREIGN KEY (OWNERID) REFERENCES user(id) ON DELETE CASCADE
);


CREATE TABLE CHOICE(
TEXT VARCHAR(50),
POLLID INTEGER,
CHOICEID INTEGER AUTO_INCREMENT,
PRIMARY KEY (POLLID,CHOICEID),
FOREIGN KEY (POLLID) REFERENCES POLL(POLLID) ON DELETE CASCADE
);


CREATE TABLE VOTE(
POLLID INTEGER,
CHOICEID INTEGER,
TIME TIMESTAMP DEFAULT NOW(),
PHONE INTEGER(20),
SESSIONID INTEGER(20),
COUNT INTEGER(10),
FOREIGN KEY (POLLID) REFERENCES POLL(POLLID) ON DELETE CASCADE,
FOREIGN KEY (CHOICEID) REFERENCES CHOICE(CHOICEID) ON DELETE CASCADE
);


CREATE TABLE receivedsms
                ( id   integer primary key auto_increment
                        , when timestamp not null default now()
                , sender varchar(32) not null
                , message varchar(500) not null
            );