INSERT INTO user (email, password) VALUES('ALICE@GMAIL.COM','PASSWORD123');
INSERT INTO registration (fname,lname,email, password) VALUES('Param','Mallela','param@gmail.com','cf2cde4d5e5670c7ab32c37e57f8bbe3$2597e87451ceeb1cc8a7fbf306d74012c9ffe8f9f524223155011109b0abc38c');

INSERT INTO POLL(QUESTION,TEXTMSG)
VALUES ('Which Mobile do you use','YTe');

INSERT INTO CHOICE(TEXT,POLLID) VALUES ('Samsung S7',1);
INSERT INTO CHOICE(TEXT,POLLID) VALUES ('Iphone 6s',1);
INSERT INTO CHOICE(TEXT,POLLID) VALUES ('Nexus 6p',1);
INSERT INTO CHOICE(TEXT,POLLID) VALUES ('Surface Phone',1);

INSERT INTO POLL(QUESTION,OWNERID,CREATED,STARTDATE,ENDDATE,TEXTMSG,URL,STATUS)
VALUES ('1',2,TO_DATE('20160215','YYYYMMDD'),TO_DATE('20160215','YYYYMMDD'),
TO_DATE('20160315','YYYYMMDD'),'YeTe','123','online');


INSERT INTO POLL(QUESTION,OWNERID,CREATED,STARTDATE,ENDDATE,TEXTMSG,URL,STATUS)
VALUES ('Which of the following heroes do you like??',1,TO_DATE('20160506','YYYYMMDD'),TO_DATE('20170215','YYYYMMDD'),
TO_DATE('20160315','YYYYMMDD'),'arcll','2938','online');

INSERT INTO CHOICE(TEXT,POLLID) VALUES ('Iron-Man',3);
INSERT INTO CHOICE(TEXT,POLLID) VALUES ('Captain-America',3);
INSERT INTO CHOICE(TEXT,POLLID) VALUES ('War Machine',3);
INSERT INTO CHOICE(TEXT,POLLID) VALUES ('Black Widow',3);
INSERT INTO CHOICE(TEXT,POLLID) VALUES ('Black Panther',3);
INSERT INTO CHOICE(TEXT,POLLID) VALUES ('The vision',3);
INSERT INTO CHOICE(TEXT,POLLID) VALUES ('Spider-Man',3);

